### ISSUE TITLE
Multiple directives error

### ISSUE THREAD

**Issue by kmartinezmedia** [uploadcare/angular-uploadcare#10]
I'm getting an Error: [$compile:multidir] Multiple directives [input, uploadcareWidget] asking for new/isolated scope on: <input uploadcare-widget="">

 I am trying to use this directive in an Ionic project. Any idea how I might be able to fix this or known conflicts when using in Ionic or ui-router based projects? 

![screen shot 2015-06-06 at 6 20 24 pm](https://cloud.githubusercontent.com/assets/6308123/8021715/e2a80c84-0c78-11e5-8817-6db99641721e.png)

**Comment by dmitry-mukhin** [comment]
@kmartinezmedia does this happen in regular Angular (not ionic)?

**Comment by kmartinezmedia** [comment]
Works fine in regular angular when I created codepen

**Comment by dmitry-mukhin** [comment]
Can you tell what conflicting "input" directive is.
Is it Ionic's or yours?

**Comment by kmartinezmedia** [comment]
This was a conflicting error with another input directive I had created and forgot about. Sorry!
