### ISSUE TITLE
option for custom class name and input file wording

### ISSUE THREAD

**Issue by mez** [uploadcare/angular-uploadcare#11]
A way to say for example...
 
input(data-classname='btn btn-block' data-wording="Choose Profile pic")

Which would result in a button element with the css class and wording would be a cool enhancement. 

Great directive btw!

**Comment by dmitry-mukhin** [comment]
@mez,
1. wording is changed via [custom locale](https://uploadcare.com/documentation/widget/#custom-localization)
2. not sure what you mean about css class. you control class of input element, widget button may be selected unambiguously

does this answer your questions?

**Comment by mez** [comment]
Yes thank you!
