### ISSUE TITLE
how to get the uuid for the uploaded image 

### ISSUE THREAD

**Issue by HDaghash** [uploadcare/angular-uploadcare#15]
how to get the uuid for the uploaded image  ,
Thanks for the awesome uploader :)

**Comment by HDaghash** [comment]
currently i get it with stupid way : $('input[name="my_file"]').val()  :+1:

**Comment by dmitry-mukhin** [comment]
@HDaghash that's the one way (as widget indeed populates the input with the URL).
The best way is to subscribe to widget's `onUploadComplete` or `onChange` events (both are exposed in directive), and get much more info for uploaded files.
