### ISSUE TITLE
angular two way databinding not working for hidden fields

### ISSUE THREAD

**Issue by Morpho** [uploadcare/angular-uploadcare#2]
It seems like the two way databinding with ng-model is not working, because its a hidden input field and angular doesnt provide support for hidden input fields. That way it is not very practicable for angularjs.

**Comment by dmitry-mukhin** [comment]
@Morpho do you think you can provide a patch for this? our hands are a bit tied up right now.

**Comment by Morpho** [comment]
https://github.com/uploadcare/angular-uploadcare/pull/3
