### ISSUE TITLE
check that directive plays well with widget 2.x

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/angular-uploadcare#4]
There were some backward incompatible changes in widget version 2.0.0.
Especially `path-value` is on by default now.

See [changelog](https://github.com/uploadcare/uploadcare-widget/blob/master/HISTORY.markdown)

**Comment by dmitry-mukhin** [comment]
@Morpho, can you please look into it?

**Comment by Morpho** [comment]
Sorry I don't know what you mean and I don't know what's path-value. The widget works for me in angular now after the ngModel fix.

**Comment by dmitry-mukhin** [comment]
@Morpho does latest widget version (2.0.4) works for you?
